/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_madsys_rdma_RDMASelector */

#ifndef _Included_com_madsys_rdma_RDMASelector
#define _Included_com_madsys_rdma_RDMASelector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madsys_rdma_RDMASelector
 * Method:    InitFD
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_madsys_rdma_RDMASelector_InitFD
  (JNIEnv *, jobject);

/*
 * Class:     com_madsys_rdma_RDMASelector
 * Method:    doZero
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_madsys_rdma_RDMASelector_doZero
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madsys_rdma_RDMASelector
 * Method:    doSet
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_madsys_rdma_RDMASelector_doSet
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_madsys_rdma_RDMASelector
 * Method:    doSelect
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMASelector_doSelect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madsys_rdma_RDMASelector
 * Method:    isSet
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMASelector_isSet
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_madsys_rdma_RDMASelector
 * Method:    doFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMASelector_doFree
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
