/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_madsys_rdma_RDMASocketChannel */

#ifndef _Included_com_madsys_rdma_RDMASocketChannel
#define _Included_com_madsys_rdma_RDMASocketChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madsys_rdma_RDMASocketChannel
 * Method:    ClientInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_madsys_rdma_RDMASocketChannel_ClientInit
  (JNIEnv *, jobject);

/*
 * Class:     com_madsys_rdma_RDMASocketChannel
 * Method:    ClientCreate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMASocketChannel_ClientCreate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madsys_rdma_RDMASocketChannel
 * Method:    doConnect
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMASocketChannel_doConnect
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     com_madsys_rdma_RDMASocketChannel
 * Method:    doClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMASocketChannel_doClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madsys_rdma_RDMASocketChannel
 * Method:    doRead
 * Signature: (JLjava/lang/Object;I)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMASocketChannel_doRead
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:     com_madsys_rdma_RDMASocketChannel
 * Method:    doWrite
 * Signature: (JLjava/lang/Object;I)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMASocketChannel_doWrite
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:     com_madsys_rdma_RDMASocketChannel
 * Method:    registerMem
 * Signature: (JLjava/lang/Object;II)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMASocketChannel_registerMem
  (JNIEnv *, jobject, jlong, jobject, jint, jint);

/*
 * Class:     com_madsys_rdma_RDMASocketChannel
 * Method:    doMemCopy
 * Signature: (JLjava/lang/Object;III)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMASocketChannel_doMemCopy
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
