/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_madsys_rdma_RDMAServerSocketChannel */

#ifndef _Included_com_madsys_rdma_RDMAServerSocketChannel
#define _Included_com_madsys_rdma_RDMAServerSocketChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madsys_rdma_RDMAServerSocketChannel
 * Method:    doServerInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_madsys_rdma_RDMAServerSocketChannel_doServerInit
  (JNIEnv *, jobject);

/*
 * Class:     com_madsys_rdma_RDMAServerSocketChannel
 * Method:    doBind
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMAServerSocketChannel_doBind
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_madsys_rdma_RDMAServerSocketChannel
 * Method:    doClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMAServerSocketChannel_doClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madsys_rdma_RDMAServerSocketChannel
 * Method:    doListen
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_madsys_rdma_RDMAServerSocketChannel_doListen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madsys_rdma_RDMAServerSocketChannel
 * Method:    doAccept
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madsys_rdma_RDMAServerSocketChannel_doAccept
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
